var navigation = [ { id: 'root', name: 'root', root: true },
 { 'id': 'ID0ET', 'name': 'DE', 'parent': 'root' },
{ 'id': 'ID0EVE', 'name': 'Allgemeines', 'parent': 'ID0ET' },
{ 'id': 'ID0EWF', 'name': 'Sicherheit', 'parent': 'ID0ET' },
{ 'id': 'ID0ENAAC', 'name': 'Symbolerklärung', 'parent': 'ID0EWF' },
{ 'id': 'ID0EWKAC', 'name': 'Verwendungszweck', 'parent': 'ID0EWF' },
{ 'id': 'ID0E3PAC', 'name': 'Allgemeine Gefahrenquellen', 'parent': 'ID0EWF' },
{ 'id': 'ID0EJFAE', 'name': 'Verantwortung des Betreibers', 'parent': 'ID0EWF' },
{ 'id': 'ID0EJGAE', 'name': 'Personalanforderung', 'parent': 'ID0EWF' },
{ 'id': 'ID0EOGAE', 'name': 'Qualifikation des Personals', 'parent': 'ID0EJGAE' },
{ 'id': 'ID0EM5AE', 'name': 'Mindestalter des Personals', 'parent': 'ID0EJGAE' },
{ 'id': 'ID0E35AE', 'name': 'Unbefugte Personen', 'parent': 'ID0EJGAE' },
{ 'id': 'ID0ETBAG', 'name': 'Persönliche Schutzausrüstung', 'parent': 'ID0EWF' },
{ 'id': 'ID0ELCAG', 'name': 'Beschreibung der Schutzausrüstung', 'parent': 'ID0ETBAG' },
{ 'id': 'ID0EWEAG', 'name': 'Sicherheitseinrichtungen', 'parent': 'ID0EWF' },
{ 'id': 'ID0E1IAG', 'name': 'Lage der Sicherheitseinrichtungen', 'parent': 'ID0EWEAG' },
{ 'id': 'ID0EJNAG', 'name': 'Sicherheitsschalter "Pilz"', 'parent': 'ID0EWEAG' },
{ 'id': 'ID0E2YAG', 'name': 'Funktionsprüfung', 'parent': 'ID0EJNAG' },
{ 'id': 'ID0ED3AG', 'name': 'Not-Halt-Taster', 'parent': 'ID0EWEAG' },
{ 'id': 'ID0EXMBG', 'name': 'Funktionsprüfung', 'parent': 'ID0ED3AG' },
{ 'id': 'ID0E6PBG', 'name': 'Hauptschalter', 'parent': 'ID0EWEAG' },
{ 'id': 'ID0ENTBG', 'name': 'Sicherheitskennzeichen und Symbole auf der Maschine', 'parent': 'ID0EWF' },
{ 'id': 'ID0EXDBI', 'name': 'Sichern gegen Wiedereinschalten', 'parent': 'ID0EWF' },
{ 'id': 'ID0ES1CI', 'name': 'Arbeitsplätze, Gefahrenbereiche', 'parent': 'ID0EWF' },
{ 'id': 'ID0EN5CI', 'name': 'Ersatzteile', 'parent': 'ID0EWF' },
{ 'id': 'ID0EW6CI', 'name': 'Verhalten im Notfall', 'parent': 'ID0EWF' },
{ 'id': 'ID0E1BDI', 'name': 'Aufstiegshilfen', 'parent': 'ID0EWF' },
{ 'id': 'ID0E3DDI', 'name': 'Hebehilfen', 'parent': 'ID0EWF' },
{ 'id': 'ID0EREDI', 'name': 'Performance Level', 'parent': 'ID0EWF' },
{ 'id': 'ID0EWFDI', 'name': 'Technische Daten', 'parent': 'ID0ET' },
{ 'id': 'ID0EU3DI', 'name': 'Typenschild', 'parent': 'ID0EWFDI' },
{ 'id': 'ID0E36DI', 'name': 'Netzanschlussschild', 'parent': 'ID0EWFDI' },
{ 'id': 'ID0EQCAK', 'name': 'Transport und Montage', 'parent': 'ID0ET' },
{ 'id': 'ID0E6CAK', 'name': 'Transport', 'parent': 'ID0EQCAK' },
{ 'id': 'ID0EMTAK', 'name': 'Maschine auspacken', 'parent': 'ID0EQCAK' },
{ 'id': 'ID0EOZAK', 'name': 'Maschine aufstellen', 'parent': 'ID0EQCAK' },
{ 'id': 'ID0E1FBK', 'name': 'Aufbau und Funktion', 'parent': 'ID0ET' },
{ 'id': 'ID0EUGBK', 'name': 'Übersicht Maschine', 'parent': 'ID0E1FBK' },
{ 'id': 'ID0EOPBK', 'name': 'Arbeitsablauf', 'parent': 'ID0E1FBK' },
{ 'id': 'ID0EMSBK', 'name': 'Baugruppenbeschreibungen', 'parent': 'ID0E1FBK' },
{ 'id': 'ID0EFTBK', 'name': 'Packstoffträger', 'parent': 'ID0EMSBK' },
{ 'id': 'ID0EJCCK', 'name': 'Packstoff auflegen und bis zur Abzugseinrichtung führen', 'parent': 'ID0EFTBK' },
{ 'id': 'ID0EHLDK', 'name': 'Korrektur der Packstoffbahn-Spannung', 'parent': 'ID0EFTBK' },
{ 'id': 'ID0EHQDK', 'name': 'Packstoffbahn-Verstellung', 'parent': 'ID0EFTBK' },
{ 'id': 'ID0EZUDK', 'name': 'Formsatz', 'parent': 'ID0EMSBK' },
{ 'id': 'ID0EA3DK', 'name': 'Formsatz auswechseln', 'parent': 'ID0EZUDK' },
{ 'id': 'ID0EAIEK', 'name': 'Formsatz einrichten', 'parent': 'ID0EZUDK' },
{ 'id': 'ID0E1REK', 'name': 'Schute und Flachspreizer', 'parent': 'ID0EZUDK' },
{ 'id': 'ID0EN4EK', 'name': 'Packstoffabzug', 'parent': 'ID0EMSBK' },
{ 'id': 'ID0EQFFK', 'name': 'Wichtige Voraussetzungen für einen optimalen Packstoffabzug', 'parent': 'ID0EN4EK' },
{ 'id': 'ID0EMNFK', 'name': 'Abzugsriemen austauschen und spannen', 'parent': 'ID0EN4EK' },
{ 'id': 'ID0EMZFK', 'name': 'Längsverschluss', 'parent': 'ID0EMSBK' },
{ 'id': 'ID0EGFGK', 'name': 'Bedingungen für eine gute Längsnahtqualität', 'parent': 'ID0EMZFK' },
{ 'id': 'ID0EVTGK', 'name': 'Längssiegelband aus- und einbauen', 'parent': 'ID0EMZFK' },
{ 'id': 'ID0EV4GK', 'name': 'Formatumstellung', 'parent': 'ID0EMZFK' },
{ 'id': 'ID0EKNHK', 'name': 'Siegelband und/oder Schleifeinsatz austauschen', 'parent': 'ID0EMZFK' },
{ 'id': 'ID0EE3HK', 'name': 'Heizpatrone und/oder Temperaturfühler austauschen', 'parent': 'ID0EMZFK' },
{ 'id': 'ID0EPMAM', 'name': 'Querverschluss', 'parent': 'ID0EMSBK' },
{ 'id': 'ID0EOOAM', 'name': 'Definitionen', 'parent': 'ID0EPMAM' },
{ 'id': 'ID0EVRAM', 'name': 'Querverschließstation (Übersicht)', 'parent': 'ID0EPMAM' },
{ 'id': 'ID0E21AM', 'name': 'Antrieb und Antriebsübertragung', 'parent': 'ID0EPMAM' },
{ 'id': 'ID0EJABM', 'name': 'Backenausrichtung durch einen Test mit Kohlepapier prüfen', 'parent': 'ID0EPMAM' },
{ 'id': 'ID0ERIBM', 'name': 'Druckverteilung regulieren', 'parent': 'ID0EPMAM' },
{ 'id': 'ID0EWJCM', 'name': 'Quersiegelwerkzeuge aus- und einbauen', 'parent': 'ID0EPMAM' },
{ 'id': 'ID0EDYCM', 'name': 'Heizpatrone und/oder Temperaturfühler austauschen', 'parent': 'ID0EPMAM' },
{ 'id': 'ID0EQFDM', 'name': 'Trennmesser', 'parent': 'ID0EPMAM' },
{ 'id': 'ID0EOTDM', 'name': 'Optionale Ausrüstung', 'parent': 'ID0E1FBK' },
{ 'id': 'ID0ENUDM', 'name': 'Fotozelle', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0E61DM', 'name': 'Fotozelle ausrichten', 'parent': 'ID0ENUDM' },
{ 'id': 'ID0EJ6DM', 'name': 'Schneid- und Klebevorrichtung', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0EHKEM', 'name': 'Vorwarnung Packstoffende', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0EIREM', 'name': 'Packstoffkanten-Regelung', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0ECZEM', 'name': 'Vorabrollung Packstoffrolle', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0EILFM', 'name': 'Hinweise zum Betrieb eines Druckers', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0EHRFM', 'name': 'Einstellungen', 'parent': 'ID0EILFM' },
{ 'id': 'ID0EUZFM', 'name': 'Hinweise zum Betrieb eines Etikettierers', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0EP5FM', 'name': 'Einstellungen', 'parent': 'ID0EUZFM' },
{ 'id': 'ID0E6CGM', 'name': 'Kantensiegelung', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0EBPGM', 'name': 'Heizpatrone und/oder Temperaturfühler austauschen', 'parent': 'ID0E6CGM' },
{ 'id': 'ID0EH2GM', 'name': 'Formatumstellung', 'parent': 'ID0E6CGM' },
{ 'id': 'ID0EW4GM', 'name': 'Formatteile wechseln', 'parent': 'ID0E6CGM' },
{ 'id': 'ID0E4VHM', 'name': 'Quernahtkühlung', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0EU1HM', 'name': 'Seitenfaltvorrichtung', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0EKAIM', 'name': 'Formatteile wechseln', 'parent': 'ID0EU1HM' },
{ 'id': 'ID0ELQIM', 'name': 'Formatumstellung', 'parent': 'ID0EU1HM' },
{ 'id': 'ID0EXVIM', 'name': 'Seitenfaltvorrichtung entfernen', 'parent': 'ID0EU1HM' },
{ 'id': 'ID0E3ZIM', 'name': 'Beutelformvorrichtung', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0EYBJM', 'name': 'Bodenschieber', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0EGIJM', 'name': 'Beutelrutsche', 'parent': 'ID0EOTDM' },
{ 'id': 'ID0ECNJM', 'name': 'Bedienungs- und Anzeigeelemente', 'parent': 'ID0E1FBK' },
{ 'id': 'ID0EHNJM', 'name': 'Bedientableau', 'parent': 'ID0ECNJM' },
{ 'id': 'ID0E1SJM', 'name': 'Nebenbedientableau (Packstoffträger)', 'parent': 'ID0ECNJM' },
{ 'id': 'ID0ED1JM', 'name': 'Signalsäule', 'parent': 'ID0ECNJM' },
{ 'id': 'ID0ES4JM', 'name': 'Signalfarben und deren Bedeutung', 'parent': 'ID0ED1JM' },
{ 'id': 'ID0ENMKM', 'name': 'Tippbetrieb', 'parent': 'ID0E1FBK' },
{ 'id': 'ID0EYUKM', 'name': 'Steuerung', 'parent': 'ID0ET' },
{ 'id': 'ID0EHVKM', 'name': 'Allgemeines', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0EFXKM', 'name': 'Bedienung', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0EKXKM', 'name': 'Gesten', 'parent': 'ID0EFXKM' },
{ 'id': 'ID0ENBLM', 'name': 'Bedienelemente', 'parent': 'ID0EFXKM' },
{ 'id': 'ID0E6VMM', 'name': 'Werteingabe', 'parent': 'ID0EFXKM' },
{ 'id': 'ID0EHFNM', 'name': 'Bedienoberfläche', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0E3INM', 'name': 'Kopfzeile', 'parent': 'ID0EHFNM' },
{ 'id': 'ID0EDNOM', 'name': 'Symbolleiste', 'parent': 'ID0EHFNM' },
{ 'id': 'ID0EX4OM', 'name': 'Navigation', 'parent': 'ID0EHFNM' },
{ 'id': 'ID0ELCPM', 'name': 'Hauptsteuerung', 'parent': 'ID0EHFNM' },
{ 'id': 'ID0EQMPM', 'name': 'Seiteninhalt', 'parent': 'ID0EHFNM' },
{ 'id': 'ID0EQXPM', 'name': 'Verwaltung', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0EVXPM', 'name': 'Sprachverwaltung', 'parent': 'ID0EQXPM' },
{ 'id': 'ID0ET1PM', 'name': 'Benutzerverwaltung', 'parent': 'ID0EQXPM' },
{ 'id': 'ID0ELQAO', 'name': 'Favoriten verwalten und erstellen', 'parent': 'ID0EQXPM' },
{ 'id': 'ID0E6YAO', 'name': 'Rezepturverwaltung', 'parent': 'ID0EQXPM' },
{ 'id': 'ID0EWFBO', 'name': 'Systemmeldungen', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0EX6BO', 'name': 'OPC-UA', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0EPUIO', 'name': 'Hauptmenü', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0EG4KO', 'name': 'Maschinenwürfel', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0EZ6KO', 'name': 'Schalter/Tippen', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0ELAMO', 'name': 'Einfahren', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0ETMMO', 'name': 'Mechanische Anpassung', 'parent': 'ID0ELAMO' },
{ 'id': 'ID0E3UMO', 'name': 'Folie einrichten', 'parent': 'ID0ELAMO' },
{ 'id': 'ID0EQENO', 'name': 'Folienlauf', 'parent': 'ID0E3UMO' },
{ 'id': 'ID0EOCOO', 'name': 'Druckmarke', 'parent': 'ID0E3UMO' },
{ 'id': 'ID0EXOQO', 'name': 'Drucken', 'parent': 'ID0ELAMO' },
{ 'id': 'ID0EDVQO', 'name': 'Etikettieren', 'parent': 'ID0ELAMO' },
{ 'id': 'ID0EP2QO', 'name': 'Beutel herstellen', 'parent': 'ID0ELAMO' },
{ 'id': 'ID0EQZRO', 'name': 'Längssiegelung', 'parent': 'ID0EP2QO' },
{ 'id': 'ID0ECHSO', 'name': 'Quersiegelung', 'parent': 'ID0EP2QO' },
{ 'id': 'ID0EMFTO', 'name': 'Stager', 'parent': 'ID0ECHSO' },
{ 'id': 'ID0EPNTO', 'name': 'Stripper', 'parent': 'ID0ECHSO' },
{ 'id': 'ID0E3WTO', 'name': 'Produktabfrage', 'parent': 'ID0ECHSO' },
{ 'id': 'ID0EMBUO', 'name': 'Kühlprofil', 'parent': 'ID0ECHSO' },
{ 'id': 'ID0EKJUO', 'name': 'Premiumseal', 'parent': 'ID0ECHSO' },
{ 'id': 'ID0EQZUO', 'name': 'Seitenfalter', 'parent': 'ID0EP2QO' },
{ 'id': 'ID0EUJVO', 'name': 'Beutel befüllen', 'parent': 'ID0ELAMO' },
{ 'id': 'ID0EBRVO', 'name': 'Waage', 'parent': 'ID0EUJVO' },
{ 'id': 'ID0EEYVO', 'name': 'Ermittlung der Fallzeit', 'parent': 'ID0EUJVO' },
{ 'id': 'ID0E5CWO', 'name': 'Siegeltemperaturen', 'parent': 'ID0ELAMO' },
{ 'id': 'ID0ENKWO', 'name': 'Schaltpositionen', 'parent': 'ID0ELAMO' },
{ 'id': 'ID0EXCXO', 'name': 'Abtransport', 'parent': 'ID0ELAMO' },
{ 'id': 'ID0EZLXO', 'name': 'Inbetriebnahme', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0ETMXO', 'name': 'Produktionsdaten', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0EXVXO', 'name': 'Diagnose', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0ETPYO', 'name': 'Ferndiagnose', 'parent': 'ID0EXVXO' },
{ 'id': 'ID0EVTYO', 'name': 'Referenzpositionen einstellen', 'parent': 'ID0EYUKM' },
{ 'id': 'ID0EGXYO', 'name': 'Backenantrieb horizontal', 'parent': 'ID0EVTYO' },
{ 'id': 'ID0ELXYO', 'name': 'Referenzposition einstellen', 'parent': 'ID0EGXYO' },
{ 'id': 'ID0EK5YO', 'name': 'Backenantrieb vertikal', 'parent': 'ID0EVTYO' },
{ 'id': 'ID0EP5YO', 'name': 'Referenzposition einstellen', 'parent': 'ID0EK5YO' },
{ 'id': 'ID0E1FZO', 'name': 'Seitenfaltvorrichtung', 'parent': 'ID0EVTYO' },
{ 'id': 'ID0E6FZO', 'name': 'Referenzposition einstellen', 'parent': 'ID0E1FZO' },
{ 'id': 'ID0EINZO', 'name': 'Referenzposition überprüfen', 'parent': 'ID0E1FZO' },
{ 'id': 'ID0EDSZO', 'name': 'Schwinge unten', 'parent': 'ID0EVTYO' },
{ 'id': 'ID0EISZO', 'name': 'Referenzposition einstellen', 'parent': 'ID0EDSZO' },
{ 'id': 'ID0E2VZO', 'name': 'Schwinge Vorabrollung oben', 'parent': 'ID0EVTYO' },
{ 'id': 'ID0EAWZO', 'name': 'Referenzposition einstellen', 'parent': 'ID0E2VZO' },
{ 'id': 'ID0EVZZO', 'name': 'Installation und Inbetriebnahme', 'parent': 'ID0ET' },
{ 'id': 'ID0EE1ZO', 'name': 'Installation', 'parent': 'ID0EVZZO' },
{ 'id': 'ID0E1A1O', 'name': 'Inbetriebnahme', 'parent': 'ID0EVZZO' },
{ 'id': 'ID0EUB1O', 'name': 'Betrieb', 'parent': 'ID0ET' },
{ 'id': 'ID0E6C1O', 'name': 'Produktionsbetrieb/Tägliche Routine', 'parent': 'ID0EUB1O' },
{ 'id': 'ID0EED1O', 'name': 'Maschine einschalten', 'parent': 'ID0E6C1O' },
{ 'id': 'ID0EBM1O', 'name': 'Produktion starten', 'parent': 'ID0E6C1O' },
{ 'id': 'ID0E2T1O', 'name': 'Arbeiten während der Produktion', 'parent': 'ID0E6C1O' },
{ 'id': 'ID0EYX1O', 'name': 'Packungsnahtqualität prüfen', 'parent': 'ID0E2T1O' },
{ 'id': 'ID0EP11O', 'name': 'Packungsdichtigkeit prüfen', 'parent': 'ID0E2T1O' },
{ 'id': 'ID0EX61O', 'name': 'Verhalten bei Störungen', 'parent': 'ID0E6C1O' },
{ 'id': 'ID0EGB2O', 'name': 'Produktion beenden', 'parent': 'ID0E6C1O' },
{ 'id': 'ID0EPH2O', 'name': 'Maschine ausschalten', 'parent': 'ID0E6C1O' },
{ 'id': 'ID0EBN2O', 'name': 'Formatumstellung der Maschine', 'parent': 'ID0EUB1O' },
{ 'id': 'ID0ERQ2O', 'name': 'Reinigung', 'parent': 'ID0EUB1O' },
{ 'id': 'ID0EBR2O', 'name': 'Sicherheit bei Reinigungsarbeiten', 'parent': 'ID0ERQ2O' },
{ 'id': 'ID0EY12O', 'name': 'Reinigungs- und Desinfektionsmittel', 'parent': 'ID0ERQ2O' },
{ 'id': 'ID0EM32O', 'name': 'Reinigungsverfahren', 'parent': 'ID0ERQ2O' },
{ 'id': 'ID0E642O', 'name': 'Reinigungsplan', 'parent': 'ID0ERQ2O' },
{ 'id': 'ID0ETT5O', 'name': 'Maschine reinigen', 'parent': 'ID0ERQ2O' },
{ 'id': 'ID0EYT5O', 'name': 'Reinigung durchführen', 'parent': 'ID0ETT5O' },
{ 'id': 'ID0EKV5O', 'name': 'Arbeiten nach der Reinigung', 'parent': 'ID0ETT5O' },
{ 'id': 'ID0EAW5O', 'name': 'Reinigungsarbeiten', 'parent': 'ID0ERQ2O' },
{ 'id': 'ID0EFW5O', 'name': 'Schutzverkleidung', 'parent': 'ID0EAW5O' },
{ 'id': 'ID0EKX5O', 'name': 'Produktberührende Teile', 'parent': 'ID0EAW5O' },
{ 'id': 'ID0EFZ5O', 'name': 'Sicherheit', 'parent': 'ID0EAW5O' },
{ 'id': 'ID0EB15O', 'name': 'Packstoffträger', 'parent': 'ID0EAW5O' },
{ 'id': 'ID0EF25O', 'name': 'Vorabrollung Packstoffrolle', 'parent': 'ID0EAW5O' },
{ 'id': 'ID0EO55O', 'name': 'Kantensiegelung', 'parent': 'ID0EAW5O' },
{ 'id': 'ID0EJQ6O', 'name': 'Abzugseinrichtung', 'parent': 'ID0EAW5O' },
{ 'id': 'ID0EYX6O', 'name': 'Längssiegelband', 'parent': 'ID0EAW5O' },
{ 'id': 'ID0EYAAQ', 'name': 'Querverschließstation', 'parent': 'ID0EAW5O' },
{ 'id': 'ID0E4EAQ', 'name': 'Vakuumsystem', 'parent': 'ID0EAW5O' },
{ 'id': 'ID0EIKAQ', 'name': 'Elektrik', 'parent': 'ID0EAW5O' },
{ 'id': 'ID0E11AQ', 'name': 'Transportbänder', 'parent': 'ID0EAW5O' },
{ 'id': 'ID0EP4AQ', 'name': 'Instandhaltung', 'parent': 'ID0ET' },
{ 'id': 'ID0E15AQ', 'name': 'Wartung', 'parent': 'ID0EP4AQ' },
{ 'id': 'ID0E65AQ', 'name': 'Sicherheit bei Wartungsarbeiten', 'parent': 'ID0E15AQ' },
{ 'id': 'ID0ECKBQ', 'name': 'Wartungsplan', 'parent': 'ID0E15AQ' },
{ 'id': 'ID0ECAFQ', 'name': 'Wartungsarbeiten', 'parent': 'ID0E15AQ' },
{ 'id': 'ID0EHAFQ', 'name': 'Sicherheit', 'parent': 'ID0ECAFQ' },
{ 'id': 'ID0E2BFQ', 'name': 'Packstoffträger', 'parent': 'ID0ECAFQ' },
{ 'id': 'ID0ECGFQ', 'name': 'Vorabrollung Packstoffrolle', 'parent': 'ID0ECAFQ' },
{ 'id': 'ID0ERJFQ', 'name': 'Formsatz', 'parent': 'ID0ECAFQ' },
{ 'id': 'ID0E1MFQ', 'name': 'Abzugseinrichtung', 'parent': 'ID0ECAFQ' },
{ 'id': 'ID0EUQFQ', 'name': 'Längssiegelband', 'parent': 'ID0ECAFQ' },
{ 'id': 'ID0EKZFQ', 'name': 'Querverschließstation', 'parent': 'ID0ECAFQ' },
{ 'id': 'ID0EIDGQ', 'name': 'Beutelformvorrichtung', 'parent': 'ID0ECAFQ' },
{ 'id': 'ID0ECGGQ', 'name': 'Druckluftsystem', 'parent': 'ID0ECAFQ' },
{ 'id': 'ID0E5KGQ', 'name': 'Elektrik', 'parent': 'ID0ECAFQ' },
{ 'id': 'ID0ECPGQ', 'name': 'Vakuumsystem', 'parent': 'ID0ECAFQ' },
{ 'id': 'ID0E1PGQ', 'name': 'Transportbänder', 'parent': 'ID0ECAFQ' },
{ 'id': 'ID0EETGQ', 'name': 'Transportgurt spannen', 'parent': 'ID0E1PGQ' },
{ 'id': 'ID0E3BHQ', 'name': 'Schmierung', 'parent': 'ID0EP4AQ' },
{ 'id': 'ID0E2CHQ', 'name': 'Packstoffträger', 'parent': 'ID0E3BHQ' },
{ 'id': 'ID0EGPHQ', 'name': 'Kantensiegelung', 'parent': 'ID0E3BHQ' },
{ 'id': 'ID0EEFIQ', 'name': 'Abzugseinrichtung', 'parent': 'ID0E3BHQ' },
{ 'id': 'ID0EQRIQ', 'name': 'Seitenfaltvorrichtung', 'parent': 'ID0E3BHQ' },
{ 'id': 'ID0E34IQ', 'name': 'Querverschließstation', 'parent': 'ID0E3BHQ' },
{ 'id': 'ID0ED5KQ', 'name': 'Störungen', 'parent': 'ID0ET' },
{ 'id': 'ID0EC6KQ', 'name': 'Nachrichtenliste', 'parent': 'ID0ED5KQ' },
{ 'id': 'ID0EWKWQ', 'name': 'Störungen des Maschinenlaufs', 'parent': 'ID0ED5KQ' },
{ 'id': 'ID0ECQWQ', 'name': 'Störungen der Packstoffzuführung', 'parent': 'ID0ED5KQ' },
{ 'id': 'ID0EFXWQ', 'name': 'Störungen bei der Längsnahtbildung', 'parent': 'ID0ED5KQ' },
{ 'id': 'ID0EX5WQ', 'name': 'Störungen bei der Quernahtbildung', 'parent': 'ID0ED5KQ' },
{ 'id': 'ID0EWIXQ', 'name': 'Fehlerhafte Beutel', 'parent': 'ID0ED5KQ' },
{ 'id': 'ID0EWOXQ', 'name': 'Außerbetriebnahme', 'parent': 'ID0ET' },
{ 'id': 'ID0EFPXQ', 'name': 'Abbau', 'parent': 'ID0EWOXQ' },
{ 'id': 'ID0E3UXQ', 'name': 'Entsorgung', 'parent': 'ID0EWOXQ' },
{ 'id': 'ID0EB5XQ', 'name': 'Lagerung', 'parent': 'ID0EWOXQ' },
{ 'id': 'ID0EF6XQ', 'name': 'Wiederinbetriebnahme', 'parent': 'ID0EWOXQ' },
{ 'id': 'ID0EAAYQ', 'name': 'EG-Konformitätserklärung', 'parent': 'ID0ET' },
{ 'id': 'ID0ECCYQ', 'name': 'Abkürzungsverzeichnis', 'parent': 'ID0ET' },
{ 'id': 'ID0ERFZQ', 'name': 'Glossar', 'parent': 'ID0ET' } ];