Name: ConfigData
Id: g=18d00ca32590039c68db53f531c8e935
Type: FolderType
Children:
- Name: List1
  Id: g=283c937c08f658c34e5a3e1e39a1f584
  Type: BaseDataVariableType
  DataType: Int32
  Value: 1
- Name: List2
  Id: g=f55277a00c4223f7cd0069726e732e36
  Type: BaseDataVariableType
  DataType: Int32
  Value: 2
- Name: List3
  Id: g=c2edd51b054b6928a738b37e2853f39f
  Type: BaseDataVariableType
  DataType: Int32
  Value: 3
- Name: MachineType_BS
  Id: g=be01b7f1b66e728872b5efb698407848
  Type: BaseDataVariableType
  DataType: String
  Value: "BS"
- Name: MachineType_BV
  Id: g=a5f723e6c1b86df48aa1490a809066c8
  Type: BaseDataVariableType
  DataType: String
  Value: "BV"
- Name: MachineType_CM
  Id: g=c08e81ee767758237d38ff0e981f28c5
  Type: BaseDataVariableType
  DataType: String
  Value: "CM"
- Name: MachineType_EC
  Id: g=c6ad39f4c2d1552d6c09128cdef33b33
  Type: BaseDataVariableType
  DataType: String
  Value: "EC"
- Name: MachineType_EE
  Id: g=dc227781933b4564a1b19d4c421e997f
  Type: BaseDataVariableType
  DataType: String
  Value: "EE"
- Name: MachineType_ELD
  Id: g=6e50d52d2d77abf6d56384e75e8d0312
  Type: BaseDataVariableType
  DataType: String
  Value: "ELD"
- Name: MachineType_ELS
  Id: g=cf0e68b3514f2017d896b488020348bd
  Type: BaseDataVariableType
  DataType: String
  Value: "ELS"
- Name: MachineType_ETIS_ETIL
  Id: g=4483484302fb350d6fb203ddd452def3
  Type: BaseDataVariableType
  DataType: String
  Value: "ETIS_ETIL"
- Name: MachineType_EW
  Id: g=7cf1b8111ce76fa52bbfd78d9a9b5e44
  Type: BaseDataVariableType
  DataType: String
  Value: "EW"
